from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow_en', models.CharField(default='SS 2026 Collection', max_length=200)),
                ('hero_eyebrow_ar', models.CharField(blank=True, default='مجموعة SS 2026', max_length=200)),
                ('hero_eyebrow_fr', models.CharField(blank=True, default='Collection SS 2026', max_length=200)),
                ('hero_title_line1_en', models.CharField(default='MOVE', max_length=100)),
                ('hero_title_line1_ar', models.CharField(blank=True, default='تحرك', max_length=100)),
                ('hero_title_line1_fr', models.CharField(blank=True, default='BOUGE', max_length=100)),
                ('hero_title_line2_en', models.CharField(default='BY', max_length=100)),
                ('hero_title_line2_ar', models.CharField(blank=True, default='في', max_length=100)),
                ('hero_title_line2_fr', models.CharField(blank=True, default='DE', max_length=100)),
                ('hero_title_line3_en', models.CharField(default='NIGHT', max_length=100)),
                ('hero_title_line3_ar', models.CharField(blank=True, default='الليل', max_length=100)),
                ('hero_title_line3_fr', models.CharField(blank=True, default='NUIT', max_length=100)),
                ('hero_subtitle_en', models.CharField(default='Engineered for the grind. Designed for the streets. Where performance meets obsession.', max_length=300)),
                ('hero_subtitle_ar', models.CharField(blank=True, default='مصمم للصراع. مصنوع للشوارع. حيث الأداء يلتقي الهوس.', max_length=300)),
                ('hero_subtitle_fr', models.CharField(blank=True, default="Conçu pour la lutte. Créé pour les rues.", max_length=300)),
                ('hero_cta_en', models.CharField(default='Explore Collection', max_length=100)),
                ('hero_cta_ar', models.CharField(blank=True, default='استكشف المجموعة', max_length=100)),
                ('hero_cta_fr', models.CharField(blank=True, default='Explorer la Collection', max_length=100)),
                ('hero_cta2_en', models.CharField(default='View Lookbook', max_length=100)),
                ('hero_cta2_ar', models.CharField(blank=True, default='عرض اللوك بوك', max_length=100)),
                ('hero_cta2_fr', models.CharField(blank=True, default='Voir le Lookbook', max_length=100)),
                ('ticker_items_en', models.CharField(default='MOONBLOCK,STREETWEAR,GYM WEAR,SS 2026,MOVE BY NIGHT', max_length=500)),
                ('ticker_items_ar', models.CharField(blank=True, default='مونبلوك,ستريت وير,ملابس جيم,SS 2026,تحرك في الليل', max_length=500)),
                ('ticker_items_fr', models.CharField(blank=True, default='MOONBLOCK,VÊTEMENTS DE RUE,TENUE GYM,SS 2026,BOUGER LA NUIT', max_length=500)),
                ('new_arrivals_label_en', models.CharField(default='New Arrivals', max_length=100)),
                ('new_arrivals_label_ar', models.CharField(blank=True, default='وصل حديثاً', max_length=100)),
                ('new_arrivals_label_fr', models.CharField(blank=True, default='Nouveautés', max_length=100)),
                ('new_arrivals_title_en', models.CharField(default='FRESH\nDROPS', max_length=100)),
                ('new_arrivals_title_ar', models.CharField(blank=True, default='أحدث\nالإصدارات', max_length=100)),
                ('new_arrivals_title_fr', models.CharField(blank=True, default='NOUVELLES\nPIÈCES', max_length=100)),
                ('about_label_en', models.CharField(default='Our Story', max_length=100)),
                ('about_label_ar', models.CharField(blank=True, default='قصتنا', max_length=100)),
                ('about_label_fr', models.CharField(blank=True, default='Notre Histoire', max_length=100)),
                ('about_title_en', models.CharField(default='BUILT FOR\nTHE RELENTLESS', max_length=200)),
                ('about_title_ar', models.CharField(blank=True, default='صُنع\nللمثابرين', max_length=200)),
                ('about_title_fr', models.CharField(blank=True, default='FAIT POUR\nLES TENACES', max_length=200)),
                ('about_body1_en', models.TextField(default='Moonblock was born in the intersection of athletic discipline and street culture.')),
                ('about_body1_ar', models.TextField(blank=True, default='وُلد Moonblock في تقاطع الانضباط الرياضي وثقافة الشارع.')),
                ('about_body1_fr', models.TextField(blank=True, default="Moonblock est né à l'intersection de la discipline athlétique et de la culture de rue.")),
                ('about_body2_en', models.TextField(default="Every stitch is intentional. Every silhouette, considered. We don't follow trends. We move in cycles—like the moon.")),
                ('about_body2_ar', models.TextField(blank=True, default='كل غرزة مقصودة. كل صورة ظلية، مدروسة. لا نتبع الاتجاهات.')),
                ('about_body2_fr', models.TextField(blank=True, default='Chaque point est intentionnel. Chaque silhouette, réfléchie.')),
                ('about_cta_en', models.CharField(default='Shop Now', max_length=100)),
                ('about_cta_ar', models.CharField(blank=True, default='تسوق الآن', max_length=100)),
                ('about_cta_fr', models.CharField(blank=True, default='Acheter Maintenant', max_length=100)),
                ('stat1_value', models.CharField(default='4K+', max_length=20)),
                ('stat1_label_en', models.CharField(default='Community', max_length=50)),
                ('stat1_label_ar', models.CharField(blank=True, default='المجتمع', max_length=50)),
                ('stat1_label_fr', models.CharField(blank=True, default='Communauté', max_length=50)),
                ('stat2_value', models.CharField(default='32', max_length=20)),
                ('stat2_label_en', models.CharField(default='Products', max_length=50)),
                ('stat2_label_ar', models.CharField(blank=True, default='منتج', max_length=50)),
                ('stat2_label_fr', models.CharField(blank=True, default='Produits', max_length=50)),
                ('stat3_value', models.CharField(default='100%', max_length=20)),
                ('stat3_label_en', models.CharField(default='No Compromise', max_length=50)),
                ('stat3_label_ar', models.CharField(blank=True, default='بلا تنازل', max_length=50)),
                ('stat3_label_fr', models.CharField(blank=True, default='Sans Compromis', max_length=50)),
                ('categories_label_en', models.CharField(default='Shop by Category', max_length=100)),
                ('categories_label_ar', models.CharField(blank=True, default='تسوق حسب الفئة', max_length=100)),
                ('categories_label_fr', models.CharField(blank=True, default='Acheter par Catégorie', max_length=100)),
                ('categories_title_en', models.CharField(default='EXPLORE', max_length=100)),
                ('categories_title_ar', models.CharField(blank=True, default='استكشف', max_length=100)),
                ('categories_title_fr', models.CharField(blank=True, default='EXPLORER', max_length=100)),
                ('newsletter_label_en', models.CharField(default='Stay in orbit', max_length=100)),
                ('newsletter_label_ar', models.CharField(blank=True, default='ابقَ في المدار', max_length=100)),
                ('newsletter_label_fr', models.CharField(blank=True, default='Restez en orbite', max_length=100)),
                ('newsletter_title_en', models.CharField(default='JOIN THE BLOCK', max_length=100)),
                ('newsletter_title_ar', models.CharField(blank=True, default='انضم إلى البلوك', max_length=100)),
                ('newsletter_title_fr', models.CharField(blank=True, default='REJOIGNEZ LE BLOCK', max_length=100)),
                ('newsletter_sub_en', models.CharField(default='Early access to drops. Zero spam. Pure Moonblock.', max_length=200)),
                ('newsletter_sub_ar', models.CharField(blank=True, default='وصول مبكر للإصدارات. لا بريد عشوائي.', max_length=200)),
                ('newsletter_sub_fr', models.CharField(blank=True, default='Accès anticipé aux drops. Zéro spam.', max_length=200)),
                ('footer_tagline_en', models.CharField(default='Streetwear and gym wear for those who move by night and grind by day.', max_length=300)),
                ('footer_tagline_ar', models.CharField(blank=True, default='ملابس شارع وجيم لمن يتحرك ليلاً ويكد نهاراً.', max_length=300)),
                ('footer_tagline_fr', models.CharField(blank=True, default='Streetwear et tenue de gym pour ceux qui bougent la nuit.', max_length=300)),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('tiktok_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('nav_shop_en', models.CharField(default='Shop', max_length=50)),
                ('nav_shop_ar', models.CharField(blank=True, default='تسوق', max_length=50)),
                ('nav_shop_fr', models.CharField(blank=True, default='Boutique', max_length=50)),
                ('nav_gym_en', models.CharField(default='Gym', max_length=50)),
                ('nav_gym_ar', models.CharField(blank=True, default='جيم', max_length=50)),
                ('nav_gym_fr', models.CharField(blank=True, default='Gym', max_length=50)),
                ('nav_streetwear_en', models.CharField(default='Streetwear', max_length=50)),
                ('nav_streetwear_ar', models.CharField(blank=True, default='ستريت وير', max_length=50)),
                ('nav_streetwear_fr', models.CharField(blank=True, default='Streetwear', max_length=50)),
                ('nav_lookbook_en', models.CharField(default='Lookbook', max_length=50)),
                ('nav_lookbook_ar', models.CharField(blank=True, default='لوك بوك', max_length=50)),
                ('nav_lookbook_fr', models.CharField(blank=True, default='Lookbook', max_length=50)),
                ('nav_about_en', models.CharField(default='About', max_length=50)),
                ('nav_about_ar', models.CharField(blank=True, default='حول', max_length=50)),
                ('nav_about_fr', models.CharField(blank=True, default='À Propos', max_length=50)),
                ('nav_shopnow_en', models.CharField(default='Shop Now', max_length=50)),
                ('nav_shopnow_ar', models.CharField(blank=True, default='تسوق الآن', max_length=50)),
                ('nav_shopnow_fr', models.CharField(blank=True, default='Acheter', max_length=50)),
            ],
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Name (AR)')),
                ('name_fr', models.CharField(blank=True, max_length=100, verbose_name='Name (FR)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={'verbose_name_plural': 'Categories', 'ordering': ['order', 'name_en']},
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (AR)')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='Title (FR)')),
                ('caption_en', models.CharField(blank=True, max_length=400, verbose_name='Caption (EN)')),
                ('caption_ar', models.CharField(blank=True, max_length=400, verbose_name='Caption (AR)')),
                ('caption_fr', models.CharField(blank=True, max_length=400, verbose_name='Caption (FR)')),
                ('image', models.ImageField(upload_to='lookbook/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Lookbook Item'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (AR)')),
                ('name_fr', models.CharField(blank=True, max_length=200, verbose_name='Name (FR)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Main Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 2 (hover)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 3')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available_sizes', models.CharField(default='S,M,L,XL', help_text='Comma-separated: XS,S,M,L,XL,XXL', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
