# Generated by Django 4.2.26 on 2026-02-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body1_ar',
            field=models.TextField(blank=True, default='وُلد Moonblock في تقاطع الانضباط الرياضي وثقافة الشارع. نصنع قطعاً تحملك من جلسات التدريب قبل الفجر إلى سباقات المدينة في منتصف الليل—دون تنازل عن الأسلوب أو الوظيفة.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body1_en',
            field=models.TextField(default='Moonblock was born in the intersection of athletic discipline and street culture. We create pieces that carry you from pre-dawn training sessions to late-night city runs—without compromise on style or function.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body1_fr',
            field=models.TextField(blank=True, default="Moonblock est né à l'intersection de la discipline athlétique et de la culture de rue. Nous créons des pièces qui vous portent des sessions d'entraînement avant l'aube aux courses nocturnes en ville—sans compromis sur le style ou la fonction."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body2_ar',
            field=models.TextField(blank=True, default='كل غرزة مقصودة. كل صورة ظلية، مدروسة. لا نتبع الاتجاهات. نتحرك في دورات—مثل القمر.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body2_fr',
            field=models.TextField(blank=True, default='Chaque point est intentionnel. Chaque silhouette, réfléchie. Nous ne suivons pas les tendances. Nous nous mouvons en cycles—comme la lune.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_tagline_fr',
            field=models.CharField(blank=True, default='Streetwear et tenue de gym pour ceux qui bougent la nuit et travaillent le jour.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_fr',
            field=models.CharField(blank=True, default="Conçu pour la lutte. Créé pour les rues. Là où la performance rencontre l'obsession.", max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_sub_ar',
            field=models.CharField(blank=True, default='وصول مبكر للإصدارات. لا بريد عشوائي. مونبلوك خالص.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_sub_fr',
            field=models.CharField(blank=True, default='Accès anticipé aux drops. Zéro spam. Pur Moonblock.', max_length=200),
        ),
    ]
