# Generated by Django 4.2.26 on 2026-02-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_unify_sections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymSection',
        ),
    ]
